# Configure Netlify builds - see https://docs.netlify.com/configure-builds/file-based-configuration

[build]
  command = "npm run build"
  publish = ".vuepress/dist"

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/handbook/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
[[headers]]
  for = "/resources/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
