name: Checks
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: { node-version: 12.x }
    - name: Setup
      run: |
        npm install
        git fetch origin master # have master available for comparison

    # run checks
    - name: ⭐ Linters
      run: npm run lint
    - name: ⭐ Spellcheck
      run: npm run spellcheck
      continue-on-error: true
      env:
        FORCE_COLOR: 1
    - name: ⭐ Build
      run: npm run build
