name: Lint

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
    
      - name: Install dependencies
        run: pnpm install
    
      - name: Run Prettier
        run: pnpm exec prettier --check "**/*.{js,jsx,ts,tsx,json,css,md}"
