name: Lint

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install pnpm
        run: npm install -g pnpm
    
      - name: Install dependencies
        run: pnpm install
    
      - name: Run Prettier
        run: pnpm exec prettier --check "**/*.{js,jsx,ts,tsx,json,css,md}"
